### ISSUE TITLE
Remove need to press Teensy reset button for every upload

### ISSUE THREAD

**Issue by ssilverman** [platformio/platform-teensy#19] opened 2017-03-14 19:30 UTC
The Arduino IDE seems to be able to do this via that Teensy GUI program. Is there a way for PlatformIO to do this as well?

**Comment by ivankravets** [comment] 2017-03-14 19:57
Duplicate of https://github.com/platformio/platform-teensy/issues/13

**Closed by ivankravets** 2017-03-14 19:57 UTC
Labels: duplicate
